spring.application.name=notifiy

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


spring.jpa.hibernate.ddl-auto=validate

jwt.access.key=${JWT_ACCESS_KEY}
jwt.refresh.key=${JWT_REFRESH_KEY   }

jwt.expiration.access.ms=${JWT_EXPIRATION_ACCESS}
jwt.expiration.refresh.ms=${JWT_EXPIRATION_REFRESH}