spring.application.name=notifiy
#
# DB connection setup
#
spring.datasource.url=jdbc:postgresql://localhost:5433/notify_app
spring.datasource.username=notify
spring.datasource.password=notify
#
# prevent spring from changing schema (flyway control it)
#
spring.jpa.hibernate.ddl-auto=validate
